{% set name = "atomate2" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomate2-{{ version }}.tar.gz
  sha256: f77f8b2cf365bdcd5f91820674a91277b4a7d3a58910db9fdf5f6d429ccc9133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - click
    - custodian >=2019.8.24
    - jobflow >=0.1.5
    - monty
    - numpy
    - pydantic
    - pymatgen >=2022.3.22
    - python >=3.6
    - pyyaml

test:
  imports:
    - atomate2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://materialsproject.github.io/atomate2/
  summary: atomate2 is a library of materials science workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
