{% set name = "atomate2" %}
{% set version = "0.0.20" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/atomate2-{{ version }}.tar.gz
  sha256: 9ffec5adc5b7c1e8b9589d26b18e37114ecba6ccb6a52550820f6d049be17127

build:
  entry_points:
    - atm = atomate2.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - versioningit >=1.0,<2.dev0
    - wheel
    - pip
  run:
    - pymongo <=4.10.1
    - python >={{ python_min }}
    - pyyaml
    - click
    - custodian >=2024.4.18
    - emmet-core >=0.84.3rc3
    - jobflow >=0.1.11
    - monty >=2024.12.10
    - numpy
    - pydantic-settings >=2.0.3
    - pydantic >=2.0.1
    - pymatgen >=2024.11.13

test:
  imports:
    - atomate2
  commands:
    - pip check
    - atm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://materialsproject.github.io/atomate2/
  summary: atomate2 is a library of materials science workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
