{% set name = "atomate2" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomate2-{{ version }}.tar.gz
  sha256: 68b4eb43cc3135988b1b0b7dcd9911b3ce7cc298a918475fa9eaf7cd220cea03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - click
    - custodian >=2019.8.24
    - jobflow >=0.1.5
    - monty
    - numpy
    - pydantic
    - pymatgen >=2022.3.22
    - python >=3.6
    - pyyaml

test:
  imports:
    - atomate2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://materialsproject.github.io/atomate2/
  summary: atomate2 is a library of materials science workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
