{% set name = "atomate2" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomate2-{{ version }}.tar.gz
  sha256: eacdf09325f1f23805bb68ddfef81a332b750e52ccadaca4bb9d5515d0d43dfb

build:
  entry_points:
    - atm = atomate2.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - versioningit >=1.0,<2.dev0
    - wheel
    - pip
  run:
    - python >=3.9
    - pyyaml
    - click
    - custodian >=2024.4.18
    - emmet-core >=0.82.2
    - jobflow >=0.1.11
    - monty >=2024.7.30
    - numpy
    - pydantic-settings >=2.0.3
    - pydantic >=2.0.1
    - pymatgen >=2024.6.4

test:
  imports:
    - atomate2
  commands:
    - pip check
    - atm --help
  requires:
    - pip

about:
  home: https://materialsproject.github.io/atomate2/
  summary: atomate2 is a library of materials science workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
