{% set name = "atomate2" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomate2-{{ version }}.tar.gz
  sha256: 660385858fdc182f58fddb3dedf08054b184e4172cc0b35aa528e22b857af6a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - click
    - custodian >=2019.8.24
    - jobflow >=0.1.5
    - monty
    - numpy
    - pydantic
    - pymatgen >=2022.3.22
    - python
    - pyyaml

test:
  imports:
    - atomate2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://materialsproject.github.io/atomate2/
  summary: atomate2 is a library of materials science workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
