{% set name = "atomate2" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomate2-{{ version }}.tar.gz
  sha256: 977b4c99defb885a165d35e40795d308364c1b23d2ef95a60b7469fa70dd1153

build:
  entry_points:
    - atm = atomate2.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - versioningit >=1.0,<2.dev0
    - wheel
    - pip
  run:
    - python >=3.9
    - pyyaml
    - click
    - custodian >=2023.3.10
    - emmet-core >=0.70.5
    - jobflow >=0.1.11
    - monty >=2023.9.25
    - numpy
    - pydantic-settings >=2.0.3
    - pydantic >=2.0.1,<2.5.2
    - pymatgen >=2023.12.18

test:
  imports:
    - atomate2
  commands:
    - pip check
    - atm --help
  requires:
    - pip

about:
  home: https://materialsproject.github.io/atomate2/
  summary: atomate2 is a library of materials science workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
